# Default values for kube-upgrade.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Controller image configuration
upgradeController:
  repository: ghcr.io/heathcliff26/kube-upgrade-controller
  tag: ""
  pullPolicy: IfNotPresent
  # Number of replicas
  replicaCount: 2
  # Node selector
  nodeSelector: {}
  # Tolerations
  tolerations: []
  # Affinity
  affinity: {}
  # This is for setting Kubernetes Annotations to a Pod.
  annotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  labels: {}
  # This is for setting the pod security context.
  podSecurityContext: {}
  # This is for setting the container security context.
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  # This is to setup resource requests and limits.
  resources:
    requests:
      cpu: 2m
      memory: 32Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  # This is to setup the liveness and readiness probes.
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 1

# Upgraded daemon image configuration
upgraded:
  repository: ghcr.io/heathcliff26/kube-upgraded
  tag: ""

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account.
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting up webhooks.
webhooks:
  # Enable or disable the webhook server.
  # Requires cert-manager for the certificates.
  enabled: true

# RBAC configuration
rbac:
  create: true

# Fleetlock dependency configuration
fleetlock:
  # Deploy fleetlock server
  enabled: false
