---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: PLACEHOLDER_FULLNAME-webhook
  annotations:
    cert-manager.io/inject-ca-from: PLACEHOLDER_NAMESPACE/PLACEHOLDER_FULLNAME-webhook-cert
  labels:
    PLACEHOLDER_LABELS: "true"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: PLACEHOLDER_FULLNAME-webhooks
        namespace: PLACEHOLDER_NAMESPACE
        path: /mutate-kubeupgrade-heathcliff-eu-v1alpha3-kubeupgradeplan
    failurePolicy: Fail
    name: kubeupgrade.heathcliff.eu
    rules:
      - apiGroups:
          - kubeupgrade.heathcliff.eu
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
        resources:
          - kubeupgradeplans
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: PLACEHOLDER_FULLNAME-webhook
  annotations:
    cert-manager.io/inject-ca-from: PLACEHOLDER_NAMESPACE/PLACEHOLDER_FULLNAME-webhook-cert
  labels:
    PLACEHOLDER_LABELS: "true"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: PLACEHOLDER_FULLNAME-webhooks
        namespace: PLACEHOLDER_NAMESPACE
        path: /validate-kubeupgrade-heathcliff-eu-v1alpha3-kubeupgradeplan
    failurePolicy: Fail
    name: kubeupgrade.heathcliff.eu
    rules:
      - apiGroups:
          - kubeupgrade.heathcliff.eu
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
        resources:
          - kubeupgradeplans
    sideEffects: None
