{{- if .Values.rbac.create -}}
{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-upgrade.fullname" . }}
  labels:
    {{- include "kube-upgrade.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-upgrade.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kube-upgrade.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-upgrade.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-upgrade.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-upgrade.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kube-upgrade.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
