{{- if .Values.webhooks.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-upgrade.fullname" . }}-webhooks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-upgrade.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhooks.service.type }}
  ipFamilyPolicy: {{ .Values.webhooks.service.ipFamilyPolicy }}
  {{- with .Values.webhooks.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "kube-upgrade.selectorLabels" . | nindent 4 }}
{{- end }}
